package project1;
import java.util.Random;

/**
 * A Account Number class for RU banking project that defines a unique 9-digit account number.
 * 9-digit code = 3-digit area code + 2-digit account type + 4-digit random number
 *
 * @author arpeet barvalia, jonathanjohn
 */
public class AccountNumber implements Comparable<AccountNumber> {
    private static final int SEED = 9999;
    //for a fix sequence of random numbers.
    private Branch                branch;
    private AccountType             type;
    private String                number;
    //a 4-digit number generated by the Random object
    //private static final Random random = new Random();

    /**
     * Creates a new account number with the following 2 parameters.
     *
     * @param branch the branch for the new AccountNumber object.
     * @param type the type for the new AccountNumber object.
     */
    public AccountNumber(Branch branch, AccountType type ){
        this.branch = branch;
        this.type = type;
        this.number = randomNumber();
        //4 digit number with leading zeroes instead of number from 1000-9999 for the serial number
    }

    /**
     * Generates a random 4-digit number without adding an instance variable.
     *
     * @return a random 4-digit serial number
     */
    private String randomNumber(){
        return String.format("%04d", new Random().nextInt(10000));
    }

    public Branch getBranch(){
        return branch;
    }
    public AccountType getAccountType(){
        return type;
    }
    public String getSerialNumber(){
        return number;
    }

    public void setAccountType(AccountType type){
        this.type = type; 
    }

    /**
     * @param obj check if obj equals the current account number
     * @return return true if two AccountNumber objects match, if not, return false. 
     */
    @Override
    public boolean equals(Object obj){
        if( obj instanceof AccountNumber other ){
            return this.toString().equals(other.toString());
        }
        return false;
    }
    /**
     * A method that represents the Branch object as a string. 
     *
     * @return returns Branch as a string. 
     */
    @Override
    public String toString(){
        return branch.getBranchCode() + type.getCode() + number;
    }
    /**
     * A method that returns if two accounts have the same account number
     *
     * @param other object that is being compared to current accountNumber
     * @return returns 0 if equal, 1 if current accountNumber is greater than, else, -1
     */
    @Override
    public int compareTo(AccountNumber other){
        if(this.toString().compareTo(other.toString()) > 0){
            return 1;
        }
        else if(this.toString().compareTo(other.toString()) < 0){
            return -1;
        }
        else{
            return 0;
        }
    }








}






