
public class AccountNumber implements Comparable<AccountNumber> {
    private static final int SEED = 9999;
    //for a fix sequence of random numbers.
    private Branch                branch;
    private AccountType             type;
    private String                number;
    //a 4-digit number generated by the Random object











}






